Ajout de nouvelles stratégies de pilotage dans la description
mbaudin47/retraites pull request #3
Opened 2020-02-08 23:05 UTC by josephmure

- Nouvelles stratégies non financées (S_s non défini)
- Suppression de l'explication des stratégies spécifiant R_{NVs}
- Explications supplémentaires quant aux différentes stratégies
- Le code des nouvelles stratégies reste à écrire ! Plus tard...

2020-02-09 10:39 UTC, mbaudin47 requested changes
Super ! Il n'y a que quelques détails à modifer à mon avis.

2020-02-09 10:39 UTC, mbaudin47 commented on doc/Description-du-composant-retraites.ipynb
> +    "| Entrées | Sortie | Commentaire |\n",
Est-ce que tu pourrais s'il te plaît ajouter une colonne avec l'indice du pilotage ? En effet, numéroter les pilotages permet de les retrouver sans ambiguïté dans la suite.

2020-02-09 10:39 UTC, mbaudin47 commented on doc/Description-du-composant-retraites.ipynb
> +    "| Entrées | Sorties | Commentaire |\n",
De même, est-ce que tu peux ajouter une colonne avec les indices des pilotages ?

2020-02-09 10:39 UTC, mbaudin47 commented on doc/Description-du-composant-retraites.ipynb
> +    "| Entrées | Sorties | Commentaire |\n",
Idem.

2020-02-09 15:22 UTC, josephmure commented on doc/Description-du-composant-retraites.ipynb
> +    "| Entrées | Sortie | Commentaire |\n",
Fait

2020-02-09 15:22 UTC, josephmure commented on doc/Description-du-composant-retraites.ipynb
> +    "| Entrées | Sorties | Commentaire |\n",
Fait

2020-02-09 15:25 UTC, josephmure reviewed
Les numéros des pilotages ont été ajoutés aux tableaux.
Peux-tu s'il te plaît vérifier le code des nouveaux pilotages ?
Je n'ai retiré aucun pilotage, même si ceux qui font intervenir R_{NVs} ne sont plus mentionnés dans le fichier Description.

2020-02-09 17:27 UTC, mbaudin47 commented
Je ne suis pas très favorable pour retirer les équations qui indiquent comment fonctionnent les pilotages fondés sur RNV. On est d'accord pour dire que cette variable devrait être écartée dans nos analyse. Toutefois, 
* C'est une variable du modèle du COR (que nous n'avons malheureusement pas choisie, mais c'est ainsi). 
* Le code existe déjà et fonctionne de telle sorte que si nous effacons ces équations, le code correspondant n'aura plus de documentation mathématique. 
* Bruno a déjà rédigé du matériel sur la base de cette variable (par exemple, la page principale du README ainsi que certains articles sur Médiapart). En conséquence, si nous supprimons la documentation de ces équations, les articles ne pourront plus s'appuyer que sur le code, avec moins de facilité de faire le lien entre les résutlats et le code. Je pense en particulier à des nouveaux contributeurs qui souhaiteraient vérifier le code, les équations et les résultats. 

Si les équations des pilotages associées à RNV sont en annexe du document (à la fin du document), est-ce que cela te conviendrait : la présentation principale serait inchangée, mais le matériel serait toujours accessible. Ca te conviendrait ?

2020-02-09 17:34 UTC, mbaudin47 requested changes
Le code me semble OK. 

Il manque les tests unitaires. Ils sont dans le dossier tests. Pour chaque pilotage, un test unitaire vérifie que les variables imposées sont égales à la contrainte et que les autres variables ont les valeurs requises avec une tolérance plus ou moins exigeante : 

https://github.com/brunoscherrer/retraites/blob/master/tests/test_retraites.py

Faire les tests unitaires demande un peu de temps, mais c'est efficace et assez facile dans ce cas particulier.

2020-02-09 17:34 UTC, mbaudin47 commented on doc/Description-du-composant-retraites.ipynb
> -    "### Pilotage 1 : calcul  à âge et niveau de vie défini\n",
Il est dommage de perdre ce matériel (voir mon commentaire).

2020-02-09 17:34 UTC, mbaudin47 commented on retraites/SimulateurRetraites.py
> -        pilotage 0 : statu quo du COR
Oui, démarrer à 1 est plus logique. C'est OK.

2020-02-09 21:04 UTC, josephmure commented
Le conflit est résolu. A présent, je vais travailler à la réintégration des explications concernant les pilotages faisant intervenir R_{NVs}.

2020-02-10 10:12 UTC, josephmure commented on doc/Description-du-composant-retraites.ipynb
> -    "### Pilotage 1 : calcul  à âge et niveau de vie défini\n",
Ce matériel est réintégré avec une présentation homogène à celle des autres pilotages.

2020-02-10 10:18 UTC, josephmure commented
> Si les équations des pilotages associées à RNV sont en annexe du document (à la fin du document), est-ce que cela te conviendrait : la présentation principale serait inchangée, mais le matériel serait toujours accessible. Ca te conviendrait ?

Plutôt qu'en annexe, je les ai mis à la suite dans une rubrique "Exemples d'autres pilotages". Il n'y en a que 2, en fait. Je les ai introduits en disant que le fait de considérer en plus la variable R_NVs ouvre la possibilité d'autres pilotages et que la liste qui en est donnée n'est pas exhaustive.

2020-02-10 21:59 UTC, mbaudin47 approved these changes
C'est beau !

2020-02-10 21:59 UTC, merged

2020-02-10 21:59 UTC, josephmure commented
Attention ! je n'ai pas encore implémenté les tests !

2020-02-10 22:01 UTC, mbaudin47 commented
Ok, j'attends les tests unitaires avant de créer la PR vers Bruno.